### ISSUE TITLE
Call doesn't start on Firefox [Moto G Pure, Android 12]

### ISSUE THREAD

**Issue by rosscado** [Pedal-Intelligence/saypi-userscript#121]
sourcefull1 reports an issue with microphone acquisition/VAD startup with Firefox on Android.
> I get the green button, it turns blue when I touch it, but never glows red and turns back to green. I've checked through possible hindrances, allows and permissions. It prompts me for mic permission. I reinstalled Firefox, tried the beta. Same thing.  🤔

His device is a Moto G Pure, running Android 12.

**Comment by johncrawley** [comment]
I've been looking at this using a virtual device running on Android Studio. So far, I've been running a Pixel 8 Pro with Android 12, and have been unable to reproduce. Note that setting up a custom virtual device (to match screen dimensions) in Android Studio leaves the Google Play app uninstalled without extra config file editing. 

Some thoughts so far:
 - the issue might be hardware-specific
 - the issue might be OS-specific, but is somehow not getting triggered by the virtual device
 - the device is relatively new (2021), so performance should not be an issue
 - I need to follow up with the reporter to see how often this can be reproduced
 - are there workarounds, i.e. refreshing the page, repressing the call button after the first fail
 - do our analytics pick up any microphone connection errors?
 - since Firefox mobile has no visible developer console to average users, could we add an error alert or similar to provide information about such failures?

**Comment by rosscado** [comment]
Great suggestions, John!
I recommend we modify our analytics to report microphone connection errors.
I was going to suggest the user DM us his Javascript console log, but as you say, it's unavailable on mobile and would likely contain SPI anyway.

**Comment by rosscado** [comment]
I have added more robust error handling around microphone acquisition.
When the application is unable to access the microphone device or create a MicVAD instance from it, rather than failing silently it will:
- reject the pending promise (`acquireMicrophone` service - `AudioInputMachine.ts`)
- log the error to the console
- display an appropriate user-friendly message to the user indicating what's gone wrong and what they can do, in their own language
<img width="1100" alt="mic error notification" src="https://github.com/user-attachments/assets/cddea768-24fa-4b88-b929-92e08e7f2e30">


I have not yet captured the error event in our analytics reporting system, as I think this might be sufficient, but it's something we could do relatively easily if necessary.

**Comment by rosscado** [comment]
sourcefull1 reports the issue is resolved in v1.6.6. 
> @John Crawley , @Ross Cadogan , I don't know what the change was, 🤔 but Say, Pi works fine on my Moto G Pure/Android 12 with both Firefox and Kiwi. 🎉 Don't know what my problem was before. Also, for the record, I finally thought to try my old Moto G Play/Android 11--does fine with both. ⛵🌤️ I like the interrupt button much better than auto. 🌻😎🕺
