### ISSUE TITLE
Choppy immersive mode animations for Firefox on Android

### ISSUE THREAD

**Issue by johncrawley** [Pedal-Intelligence/saypi-userscript#122]
Chiara Maria Cervetta reports an issue with animation performance in immersive mode, with Firefox on Android.

> While using the Immersive Mode, the animation lags. It's just an optical bug. The Immersive Mode animation doesn't flow but looks jerky

Running on a Google Pixel 7 Pro smartphone with Android 15

**Comment by johncrawley** [comment]
I think I can reproduce this. The animation on Firefox Android does appear to have less frames than Kiwi Android. This could be due to the rendering engines. It appears to be more noticeable for the user-speaking and transcribing animations, but there is also an apparant reduction in framerate for the default animation when the microphone is listening.

A number of mitigations can be tested such as forcing 3D, or using the will-change property in CSS.

**Comment by rosscado** [comment]
Thanks for documenting this, John. The immersive mode animations are pretty compute-heavy - we've probably just been getting away with it because Chromium browsers are so fast. I've seen similar choppiness on lower-powered devices before. Firefox seems to make it more obvious since its rendering engine isn't as optimized for these animations as Chrome's.

We could probably make some performance improvements to the current SVG+CSS animations. If those aren't enough, we might need to look at the deeper refactor proposed in #73.
